# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalMessages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SignalMessages.proto',
  package='',
  serialized_pb='\n\x14SignalMessages.proto\":\n\x0bSignalLevel\x12\x13\n\x08signalID\x18\x01 \x02(\x05:\x01\x31\x12\x16\n\x0bsignalLevel\x18\x02 \x02(\x02:\x01\x30\"D\n\x10SignalInstantVal\x12\x13\n\x08signalID\x18\x01 \x02(\x05:\x01\x31\x12\x1b\n\x10signalInstantVal\x18\x02 \x02(\x02:\x01\x30\"\x1e\n\x07Impulse\x12\x13\n\x08signalID\x18\x01 \x02(\x05:\x01\x31\"N\n\tLinearFFT\x12\x13\n\x08signalID\x18\x01 \x02(\x05:\x01\x31\x12\x1a\n\x0f\x66undamentalFreq\x18\x02 \x02(\x02:\x01\x30\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x02\x42\x02\x10\x01\"\xed\x01\n\x06LogFFT\x12\x13\n\x08signalID\x18\x01 \x01(\x05:\x01\x31\x12\x17\n\x0f\x66undamentalFreq\x18\x02 \x01(\x02\x12\r\n\x05\x62\x61nd1\x18\x03 \x01(\x02\x12\r\n\x05\x62\x61nd2\x18\x04 \x01(\x02\x12\r\n\x05\x62\x61nd3\x18\x05 \x01(\x02\x12\r\n\x05\x62\x61nd4\x18\x06 \x01(\x02\x12\r\n\x05\x62\x61nd5\x18\x07 \x01(\x02\x12\r\n\x05\x62\x61nd6\x18\x08 \x01(\x02\x12\r\n\x05\x62\x61nd7\x18\t \x01(\x02\x12\r\n\x05\x62\x61nd8\x18\n \x01(\x02\x12\r\n\x05\x62\x61nd9\x18\x0b \x01(\x02\x12\x0e\n\x06\x62\x61nd10\x18\x0c \x01(\x02\x12\x0e\n\x06\x62\x61nd11\x18\r \x01(\x02\x12\x0e\n\x06\x62\x61nd12\x18\x0e \x01(\x02\"K\n\x08TimeInfo\x12\x18\n\tisPlaying\x18\x01 \x02(\x08:\x05\x66\x61lse\x12\x10\n\x05tempo\x18\x02 \x02(\x02:\x01\x30\x12\x13\n\x08position\x18\x03 \x02(\x02:\x01\x30\x42\x10\x42\x0eSignalMessages')




_SIGNALLEVEL = _descriptor.Descriptor(
  name='SignalLevel',
  full_name='SignalLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signalID', full_name='SignalLevel.signalID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signalLevel', full_name='SignalLevel.signalLevel', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=82,
)


_SIGNALINSTANTVAL = _descriptor.Descriptor(
  name='SignalInstantVal',
  full_name='SignalInstantVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signalID', full_name='SignalInstantVal.signalID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signalInstantVal', full_name='SignalInstantVal.signalInstantVal', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=152,
)


_IMPULSE = _descriptor.Descriptor(
  name='Impulse',
  full_name='Impulse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signalID', full_name='Impulse.signalID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=184,
)


_LINEARFFT = _descriptor.Descriptor(
  name='LinearFFT',
  full_name='LinearFFT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signalID', full_name='LinearFFT.signalID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fundamentalFreq', full_name='LinearFFT.fundamentalFreq', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='LinearFFT.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=264,
)


_LOGFFT = _descriptor.Descriptor(
  name='LogFFT',
  full_name='LogFFT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signalID', full_name='LogFFT.signalID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fundamentalFreq', full_name='LogFFT.fundamentalFreq', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band1', full_name='LogFFT.band1', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band2', full_name='LogFFT.band2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band3', full_name='LogFFT.band3', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band4', full_name='LogFFT.band4', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band5', full_name='LogFFT.band5', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band6', full_name='LogFFT.band6', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band7', full_name='LogFFT.band7', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band8', full_name='LogFFT.band8', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band9', full_name='LogFFT.band9', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band10', full_name='LogFFT.band10', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band11', full_name='LogFFT.band11', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='band12', full_name='LogFFT.band12', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=267,
  serialized_end=504,
)


_TIMEINFO = _descriptor.Descriptor(
  name='TimeInfo',
  full_name='TimeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isPlaying', full_name='TimeInfo.isPlaying', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tempo', full_name='TimeInfo.tempo', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='TimeInfo.position', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=506,
  serialized_end=581,
)

DESCRIPTOR.message_types_by_name['SignalLevel'] = _SIGNALLEVEL
DESCRIPTOR.message_types_by_name['SignalInstantVal'] = _SIGNALINSTANTVAL
DESCRIPTOR.message_types_by_name['Impulse'] = _IMPULSE
DESCRIPTOR.message_types_by_name['LinearFFT'] = _LINEARFFT
DESCRIPTOR.message_types_by_name['LogFFT'] = _LOGFFT
DESCRIPTOR.message_types_by_name['TimeInfo'] = _TIMEINFO

class SignalLevel(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNALLEVEL

  # @@protoc_insertion_point(class_scope:SignalLevel)

class SignalInstantVal(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNALINSTANTVAL

  # @@protoc_insertion_point(class_scope:SignalInstantVal)

class Impulse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IMPULSE

  # @@protoc_insertion_point(class_scope:Impulse)

class LinearFFT(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LINEARFFT

  # @@protoc_insertion_point(class_scope:LinearFFT)

class LogFFT(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGFFT

  # @@protoc_insertion_point(class_scope:LogFFT)

class TimeInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMEINFO

  # @@protoc_insertion_point(class_scope:TimeInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\016SignalMessages')
_LINEARFFT.fields_by_name['data'].has_options = True
_LINEARFFT.fields_by_name['data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
